### PR TITLE
Update the Readme to the newest version

### PR DESCRIPTION
**Pull request by Nereuxofficial**

### CODE REVIEW

**Comment by Nereuxofficial** [comment]
So turns out i have to fix a few more things for the example to work with the newest version. Am currently working on it

**Comment by Nereuxofficial** [comment]
The only issue in this version is that we can't clone NeuralNetworks. What would be the best solution to this?

**Comment by Nereuxofficial** [comment]
So the solution i have working locally is deriving Clone on the needed types but there is probably a reason why it should not be done

**Comment by sakex** [comment]
@Nereuxofficial Hey, thanks for the help! I will review the code tomorrow as I'm away today. The reason we can't clone a NeuralNetwork right now is because of the way it's implemented with raw pointers. 

The neural network for now is just a `Vec<Neuron>`, neurons themselves have a `Vec<Connection>` that contains the weights and a raw pointer to the `Neuron`s they are connected to. It's pretty unsafe if you don't provide a good topology to the network and it can't be trivially copied because copying the pointer would cause to resulting pointer to point to the adress of the original connected Neuron and not the new one. 

I can add a safe implementation of Clone tomorrow if you need it. The way I'll do it is by calculating which adress based on the original offset.

**Comment by Nereuxofficial** [comment]
Thanks for the response. I don't really know if Cloning is necessary i just tried to(with lacking understanding) port the example in the README to the newest version. There may be a better solution to the reset_players function.

**Review by sakex — APPROVED** [review]

**Comment by sakex** [comment]
I haven't updated that README in a long time, I'm merging your PR then will update with relevant new additions. Thanks for the feedback!

**Comment by sakex** [comment]
FYI, it used to be a wrapper around my C++ implementation but I rewrote it entirely in Rust, that's why there are some API changes

**Pull request merged**
